### ISSUE TITLE
Issue compiling

### ISSUE THREAD

**Issue by andpalacios** [jjhidalgo/geotransdens#1]
lto1: fatal error: bytecode stream in file ‘/home/andreap/miniconda3/envs/mypgenv/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a’ generated with LTO version 6.0 instead of the expected 6.2
compilation terminated.
lto-wrapper: fatal error: gfortran returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
Makefile:224: recipe for target 'geotransdens' failed

Hello, 

I'm getting this error when I run the Makefile. It says that it's related to the version. 
Can you put a note on your version of Ubuntu, compiler, python...please? 

Thanks
Andrea

**Comment by jjhidalgo** [comment]
Hi, Andrea.
I compiled the code with x86_64-conda_cos6-linux-gnu (gfortran 7.3.0)
The problem seems to be libpython3.7m.a  Try updating the conda installation to solve the problem.

Best,
Juan

**Comment by jjhidalgo** [comment]
Hi,
I could reproduce the error after installing anaconda and the anaconda gfortran. The error happens in both the base and pygimli environments. There are two options to solve it. 
First, to update the conda installation. However this will install mkl-service for numpy in the pygimli environment, which was not required by pygimli. You will get an error in both environments as mkl will fail to initialize. This seems a conda problem because it also happens when running forpy tests.

Second without updating conda, add -fno-lto to the compilation flags as explained in [forpy documentation](https://github.com/ylikx/forpy#using-forpy-with-anaconda). This will solve the linking error. However forpy may still have problems finding numpy.

**Comment by jjhidalgo** [comment]
You can find the solution to the numpy problem in ylikx/forpy/issues/25#
